### ISSUE TITLE
To do before proceed to wordpress

### ISSUE THREAD

**Issue by FadiZahhar** [pro-freelancer/qpulse#3]
# Before WordPress #
1. adopt a Facebook like page widget in the design concept.
2. be more creative by adding a feeling (look a like to mother theme) of the white box content. make it more appealing.
3. adopt the final comments send to you by mail.

Once these are done and approved. proceed to do the following.
1. Theme development adoptation (WordPress)
2. widget development (who we are, display of projects, social icons and contact info, message form)

the widget will have the capability to change the display upon some feature variant selections, that will be determined in the development analysis and process. 

Regards,

**Comment by FadiZahhar** [comment]
Dear Dima
kindly find the third draft link below: 

http://www.pro-solutions.net/demos/qpulse/third/

changes done:
1- like and share button for Facebook below who we are.
2- Facebook linked in color blue color same logo color.
3- replacing the open box with a good stylish one that looks perfect with the design.
4- inside the white open box adopt a new style of web font, color and bullet points design (same pattern for all pages)
5- added a testimonial section (this will be a widget that you can show or hide in the future, could hide the images or could leave them).
6- replace pro-freelancer with pro-solutions to have the appealing of a company behind the work.
PS: kindly note as I mentioned before, everything will be changeable from the CMS, so in case of data manipulation or data justification, or styling the font size, color, adding images or removing images this will be feasible by your end by using the back office.

for now if you don't have any comment on the following concept design, kindly approve the concept so I can proceed with WordPress development.

Regards,

**Comment by QPulse-Dima** [comment]
Hi Fadi, the design is good, please proceed with the development.
Have a good day,
Dima

On Thu, Sep 3, 2015 at 12:53 AM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> Dear Dima
> kindly find the third draft link below:
> 
> http://www.pro-solutions.net/demos/qpulse/third/
> 
> changes done:
> 1- like and share button for Facebook below who we are.
> 2- Facebook linked in color blue color same logo color.
> 3- replacing the open box with a good stylish one that looks perfect with
> the design.
> 4- inside the white open box adopt a new style of web font, color and
> bullet points design (same pattern for all pages)
> 5- added a testimonial section (this will be a widget that you can show or
> hide in the future, could hide the images or could leave them).
> 6- replace pro-freelancer with pro-solutions to have the appealing of a
> company behind the work.
> PS: kindly note as I mentioned before, everything will be changeable from
> the CMS, so in case of data manipulation or data justification, or styling
> the font size, color, adding images or removing images this will be
> feasible by your end by using the back office.
> 
> for now if you don't have any comment on the following concept design,
> kindly approve the concept so I can proceed with WordPress development.
> 
> Regards,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/3#issuecomment-137255935
> .

##

**Comment by FadiZahhar** [comment]
Great. Good to know. Will close this ticket then and will open a new one later.
