### ISSUE TITLE
Implementing the theme to wordpress

### ISSUE THREAD

**Issue by FadiZahhar** [pro-freelancer/qpulse#4]
# list of ToDo:
1. download wordpress on localmachine
2. prepare the development pro-freelancer theme framework
3. prepare the widgets plugins pro-freelancer framework
   assemble everything.
4. make unit test.
## Things done so far on local machine and process development.
1. Qpulse based from pro-freelancer framework Theme installed (done).
2. Qpulse Widget plugins installed based from pro-freelancer plugin development (done).
3. added the content by creating the categories and pages, with posts related to categories as a pattern concept of qpulse. (done on localmachine) need to replicate it once going live (online).
# so far developed and working :+1:
1. Who we are (double version widget) first with facebook like, second without facebook like in case you want to replicate it on the theme many times.
2. social icons with contact us: done and working, tested to add thumbler as example worked. also tested by adding the page that will open the contact info (passed) (done).
3. Testimonials : tested (passed) and reading from the back end (done).
# Still need to do:
1. expertise area widget (under development)
2. contact form send an email to and validation (under development)
3. creating a link between the navigation and the sections (under development).
4. a new news section widget (under development).
5. set the headers to be same as the open box styles (under development).

once these are done we can go live

**Comment by FadiZahhar** [comment]
Hello Dima,

# Things Done September 6: #
1. expertise area widget (tested, passed, done)
2. contact form (send aan email, validation , tested, passed, done)
3. navigation pattern logic, tested, passed, done.
4. set the haders to read design box correctly (tested, done).

## Things need to be done to deliver the project
1. news section widget (under development).
2. Upload the theme, and the plugin widget to online .
3. replicated the data on my machine to be the same online
4. test online 

PS: In case you want to go live !? does the current website is running, is it have information ! or it's OK to put everything online and test it.?
your feedback about uploading everything online is necessary to proceed.

Regards,

**Comment by QPulse-Dima** [comment]
How much time does the online test take? (how long between going online and
validating the tests?)

On Mon, Sep 7, 2015 at 1:10 AM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> Hello Dima,
> Things Done September 6: #
> 1. expertise area widget (tested, passed, done)
> 2. contact form (send aan email, validation , tested, passed, done)
> 3. navigation pattern logic, tested, passed, done.
> 4. set the haders to read design box correctly (tested, done).
> 
> Things need to be done to deliver the project
> 1. news section widget (under development).
> 2. Upload the theme, and the plugin widget to online .
> 3. replicated the data on my machine to be the same online
> 4. test online
> 
> PS: In case you want to go live !? does the current website is running, is
> it have information ! or it's OK to put everything online and test it.?
> your feedback about uploading everything online is necessary to proceed.
> 
> Regards,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/4#issuecomment-138129966
> .

##

**Comment by FadiZahhar** [comment]
it is a process of 3 hours as max. uploading files, ... check that everything is working, adding the content. and check the results,

**Comment by QPulse-Dima** [comment]
OK please proceed

On Mon, Sep 7, 2015 at 9:48 AM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> it is a process of 3 hours as max. uploading files, ... check that
> everything is working, adding the content. and check the results,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/4#issuecomment-138208250
> .

##

**Comment by FadiZahhar** [comment]
Ok will do it at late, kind from 9:00 pm to 12:00 AM tonight and send you an update.

**Comment by FadiZahhar** [comment]
Starting 3 process at the time.
1. uploading the theme
2. uploading the plugin widget
3. replicating the content

will keep you posted once test is done and website is online functional.

**Comment by FadiZahhar** [comment]
Here you go.
http://www.qpulse.fr/

all are tested and well working,
what concerns the news, I need a decision on the look and feel so I can implement as a widget.

The news categories exist online now, all I need is to assemble the concept to a widget.

these are the possibilities examples to do it:
1. http://www.pro-freelancer.info/ready_templates/ecommerce_1/news.html
2. http://www.pro-freelancer.info/ready_templates/brew-web/news.html

first concept is to display a section news that have first 3 records news as start with a pagination below. and image on the left with title and date and content on the right, in case more details is needed , instead to open the box to show more details it will animate smoothly and hide the news content of the section and display the details with a close button to go back.

the second option is the same concept of show details and close button but instead of 3 rows news will show a block of news with no images, once click on one will show the details and you can go back.

PS: since this section is new and added after we agreed on the deadline, I will implement with no charge but on my available time. and this was not agreed on the delivery date. 

for now the website is online, and I will support it as agreed till 8 of October so you can get use on how manipulating the content from the back office.

I will write a detailed documentation later, also this could take a bit of time due to the tight schedule. but you can always ask any question as you will notice how it is easy to replicate the current template by copy pasting the code inside the text editor and re-editing the content accordingly.

In case of any changes you need as example to remove testimonial and so on you can ask me to do so for now till I teached you how to use the system.

you can always sign in to the back office at http://www.qpulse.fr/wp-admin 
I hacked from  the database a username of dev and a pass of P@ssword@123 to be able to create the content for you.

you can drop an eye and I have full faith with your personal intelligent in understanding the pattern with no extra help from my part.

this issue is closed.
any feedback is appreciated.
Regards,

**Comment by QPulse-Dima** [comment]
thank you Fadi, nice job!
I believe we should have the session that we agreed upon this week, so you
can teach me how to edit things. I don't find it easy to learn it by
myself. Let me know of your availability please.

On Tue, Sep 8, 2015 at 12:21 AM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> Closed #4 https://github.com/pro-freelancer/qpulse/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/4#event-403054304.

##

**Comment by QPulse-Dima** [comment]
and yes please hide the testimonials section in the meanwhile

On Tue, Sep 8, 2015 at 7:30 AM, Dima Abou Moussa <dima.abou.moussa@gmail.com

> wrote:
> 
> thank you Fadi, nice job!
> I believe we should have the session that we agreed upon this week, so you
> can teach me how to edit things. I don't find it easy to learn it by
> myself. Let me know of your availability please.
> 
> On Tue, Sep 8, 2015 at 12:21 AM, Fadi Nicolas Zahhar <
> notifications@github.com> wrote:
> 
> > Closed #4 https://github.com/pro-freelancer/qpulse/issues/4.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pro-freelancer/qpulse/issues/4#event-403054304.
> 
> ## 

##

**Comment by QPulse-Dima** [comment]
by the way, my brother is receiving all the emails on his personal email (2
messages received from the website, that he forwarded  to me) shouldn't
they be sent to info@qpulse.fr?

On Tue, Sep 8, 2015 at 7:34 AM, Dima Abou Moussa <dima.abou.moussa@gmail.com

> wrote:
> 
> and yes please hide the testimonials section in the meanwhile
> 
> On Tue, Sep 8, 2015 at 7:30 AM, Dima Abou Moussa <
> dima.abou.moussa@gmail.com> wrote:
> 
> > thank you Fadi, nice job!
> > I believe we should have the session that we agreed upon this week, so
> > you can teach me how to edit things. I don't find it easy to learn it by
> > myself. Let me know of your availability please.
> > 
> > On Tue, Sep 8, 2015 at 12:21 AM, Fadi Nicolas Zahhar <
> > notifications@github.com> wrote:
> > 
> > > Closed #4 https://github.com/pro-freelancer/qpulse/issues/4.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/pro-freelancer/qpulse/issues/4#event-403054304.
> > 
> > ## 
> 
> ## 

##

**Comment by FadiZahhar** [comment]
you can change this from the word press settings, it is the administrator who will receive the emails. so !!!

**Comment by FadiZahhar** [comment]
I will do it all your modifications including changing the email from the back office @ afternoon . Regards,

**Comment by FadiZahhar** [comment]
set the email to info@qpulse.fr from the website, as removed the testimonials and so on.

**Comment by QPulse-Dima** [comment]
Good morning,
There are 2 things that I am unable to change:
1- in the back office I edited the page (writing consultancy) and changed
the content. It didn't change in the page (when i click view more, i still
see the old text that is different from the edited text in the back office-
page- edit page section (although I pressed update)
2- Area of expertise had a spelling mistake, it was written (experti_es_),
I was able to change it in the page but not in the dashboard.
Please advise.

On Tue, Sep 8, 2015 at 8:13 PM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> set the email to info@qpulse.fr from the website, as removed the
> testimonials and so on.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/4#issuecomment-138637658
> .

##

**Comment by FadiZahhar** [comment]
Let us set a meeting to help you face to face how to use the system, as you need to take into consideration that in the web there is something called Cache. this unnecessary loads each time from the server so it will fetch the data that was saved on your browser.

especially the fancy box that apears need to be refreshed to reload server data and not browser data.

So kindly advice when we can meet so I can handle a 30 minutes session on how to manage the website.

Regards,

**Comment by QPulse-Dima** [comment]
Are you available tomorrow? I finish work at 5 in jal el dib

**Comment by FadiZahhar** [comment]
yes but after 6! so any time after 6 is ok with me, preferable 6:30

**Comment by QPulse-Dima** [comment]
No problem i will be at starbucks then.
Regards
