### ISSUE TITLE
Add a color picker to color the title of experties

### ISSUE THREAD

**Issue by FadiZahhar** [pro-freelancer/qpulse#5]

**Comment by FadiZahhar** [comment]
You can change the title colors of expertise by doing the following:
1. go to posts in the back office.
2. filter by category by choosing Areas of Expertise
3. edit the record you want to change the color
4. navigate down below the text content 
   you will see a color picker titled  

```
expertise color title
Choose the color of the title to look good with the background image (used with q pulse expertise widget).
```

will work on the documentation and send you the link.

I made a demo with red color on the final record, you can change is as you like.
This issue is closed.
![qpulse-color-picker](https://cloud.githubusercontent.com/assets/8089881/10259380/12fdf908-6970-11e5-8456-93482bf5e3df.jpg)

**Comment by QPulse-Dima** [comment]
Hi fadi,
"Who we are" is not in the "Areas of expertise". where can I find it?

On Sat, Oct 3, 2015 at 1:47 AM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> You can change the title colors of expertise by doing the following:
> 1. go to posts in the back office.
> 2. filter by category by choosing Areas of Expertise
> 3. edit the record you want to change the color
> 4. navigate down below the text content you will see a color picker
>    titled
> 
> expertise color title
> Choose the color of the title to look good with the background image (used with q pulse expertise widget).
> 
> will work on the documentation and send you the link.
> 
> I made a demo with red color on the final record, you can change is as you
> like.
> This issue is closed.
> [image: qpulse-color-picker]
> https://cloud.githubusercontent.com/assets/8089881/10259380/12fdf908-6970-11e5-8456-93482bf5e3df.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/5#issuecomment-145174344
> .

##

**Comment by FadiZahhar** [comment]
it is not in the post section , it is on the page section in the name of who we are.

did you meant to change the color of this section ? casue what I did is for the expertise only.

anyway I'm writing the documentation now as a guide for you.

**Comment by QPulse-Dima** [comment]
Yes please thats the one i need

**Comment by FadiZahhar** [comment]
Do you want to change the color of the button ? or the title in the home page? or the title once you open the page !!!??? kindly precise to fix it for you.

**Comment by QPulse-Dima** [comment]
The title "who we are" on the home page

**Comment by FadiZahhar** [comment]
OK , Will do a solution of clolor picker for this feature also.

**Comment by FadiZahhar** [comment]
This issue was fixed as following.
doing a color picker for the page post named
titlecolor,
titlebg,
titlehover
slogoncolor

each color picker is related to something for the who we are section.
first is the color of the word on the button who we are.
second is the default background of the button
third is the hover effect color of the button who we are
fourth is the slogon color.

to be able to change them just go to pages section
find who we are
edit the content 
after the text editor you will see the color picker with each with it's proper title.

choose the right one.
and save.

this issue is cloed on October 21 2015
